name: wastsafe_app
description: WastSafe - Plataforma de reciclagem de componentes eletrônicos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
 
  cupertino_icons: ^1.0.8
  
 
  google_fonts: ^6.2.1
  
 
  http: ^1.2.2
  
 
  image_picker: ^1.1.2
  
 
  mobile_scanner: ^5.2.0
  supabase_flutter: ^2.12.4
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/logo.png
    - assets/fundo_chat.png